# Generated by Django 4.1.2 on 2023-09-15 22:01

from django.db import migrations, models
import django.db.models.deletion
import one.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('wrigth', models.CharField(max_length=30, verbose_name='Композитор')),
                ('transcription', models.CharField(max_length=30, verbose_name='Автор транскрипции')),
                ('have_score', models.BooleanField(default=False, verbose_name='Наличие партитуры')),
                ('music', models.CharField(max_length=50, validators=[one.validators.url_path_validator], verbose_name='Ссылка на музыкальный пример')),
                ('time', models.DateTimeField(auto_now=True)),
                ('band', models.PositiveSmallIntegerField(choices=[(1, 'Дуэт'), (2, 'Трио'), (3, 'Квартет'), (4, 'Квинтет'), (5, 'Секстет'), (6, 'Big Band'), (7, 'Симфо-джаз'), (8, 'Уникальный состав')], default=3, verbose_name='Состав')),
                ('style', models.PositiveSmallIntegerField(choices=[(1, 'Джаз'), (2, 'Поп'), (3, 'Кавера'), (4, 'Авторская композиция (аранжировка)'), (5, 'Музыка из кино')], default=1, verbose_name='Стиль')),
            ],
            options={
                'verbose_name': 'Композиция',
                'verbose_name_plural': 'Композиции',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SongForSearch',
            fields=[
                ('song_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='one.song')),
                ('band1', models.PositiveSmallIntegerField(choices=[(0, 'Состав не выбран'), (1, 'Дуэт'), (2, 'Трио'), (3, 'Квартет'), (4, 'Квинтет'), (5, 'Секстет'), (6, 'Big Band'), (7, 'Симфо-джаз'), (8, 'Уникальный состав')], default=0, verbose_name='Состав')),
                ('style1', models.PositiveSmallIntegerField(choices=[(0, 'Стиль не выбран'), (1, 'Джаз'), (2, 'Поп'), (3, 'Кавера'), (4, 'Авторская композиция (аранжировка)'), (5, 'Музыка из кино')], default=0, verbose_name='Стиль')),
            ],
            bases=('one.song',),
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.FileField(upload_to='media', verbose_name='Ноты')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='one.song')),
            ],
        ),
    ]
