# Generated by Django 4.1.2 on 2022-11-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='band',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Дуэт'), (2, 'Трио'), (3, 'Квартет'), (4, 'Квинтет'), (5, 'Секстет'), (6, 'Big Band'), (7, 'Симфо-джаз'), (8, 'Уникальный состав')], default=3, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='song',
            name='style',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Джаз'), (2, 'Поп'), (3, 'Кавера'), (4, 'Авторская композиция (аранжировка)'), (5, 'Музыка из кино')], default=1, verbose_name='Стиль'),
        ),
        migrations.AddField(
            model_name='song',
            name='transcription',
            field=models.CharField(default=1, max_length=30, verbose_name='Автор транскрипции'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='song',
            name='wrigth',
            field=models.CharField(max_length=30, verbose_name='Композитор'),
        ),
    ]
