# Generated by Django 4.1.2 on 2022-11-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_song_band_song_style_song_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='score',
            field=models.FileField(blank=True, null=True, upload_to='media', verbose_name='Партии'),
        ),
    ]
