# Generated by Django 4.1.2 on 2022-11-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0003_song_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music',
            field=models.SlugField(default='https://www.youtube.com/watch?v=MiZMiAMHr4o', max_length=255, verbose_name='Ссылка на музыку'),
            preserve_default=False,
        ),
    ]
