# Generated by Django 4.1.2 on 2022-11-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0005_remove_song_score_song_have_score_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='music',
            field=models.CharField(max_length=50, verbose_name='Ссылка на музыку'),
        ),
    ]
