# Generated by Django 4.1.2 on 2022-11-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_alter_song_music'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='have_score',
            field=models.BooleanField(default=False, verbose_name='Наличие партитуры'),
        ),
        migrations.AlterField(
            model_name='song',
            name='music',
            field=models.CharField(max_length=50, verbose_name='Ссылка на музыкальный пример'),
        ),
    ]
