# Generated by Django 4.1.2 on 2022-11-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0007_alter_song_have_score_alter_song_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
